// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.13.0
// source: stock.proto

package stock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UpdateStock_UpdateStock_FullMethodName = "/stock.UpdateStock/UpdateStock"
)

// UpdateStockClient is the client API for UpdateStock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateStockClient interface {
	UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error)
}

type updateStockClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateStockClient(cc grpc.ClientConnInterface) UpdateStockClient {
	return &updateStockClient{cc}
}

func (c *updateStockClient) UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error) {
	out := new(UpdateStockResponse)
	err := c.cc.Invoke(ctx, UpdateStock_UpdateStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateStockServer is the server API for UpdateStock service.
// All implementations must embed UnimplementedUpdateStockServer
// for forward compatibility
type UpdateStockServer interface {
	UpdateStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error)
	mustEmbedUnimplementedUpdateStockServer()
}

// UnimplementedUpdateStockServer must be embedded to have forward compatible implementations.
type UnimplementedUpdateStockServer struct {
}

func (UnimplementedUpdateStockServer) UpdateStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStock not implemented")
}
func (UnimplementedUpdateStockServer) mustEmbedUnimplementedUpdateStockServer() {}

// UnsafeUpdateStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateStockServer will
// result in compilation errors.
type UnsafeUpdateStockServer interface {
	mustEmbedUnimplementedUpdateStockServer()
}

func RegisterUpdateStockServer(s grpc.ServiceRegistrar, srv UpdateStockServer) {
	s.RegisterService(&UpdateStock_ServiceDesc, srv)
}

func _UpdateStock_UpdateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateStockServer).UpdateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateStock_UpdateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateStockServer).UpdateStock(ctx, req.(*UpdateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateStock_ServiceDesc is the grpc.ServiceDesc for UpdateStock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateStock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.UpdateStock",
	HandlerType: (*UpdateStockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStock",
			Handler:    _UpdateStock_UpdateStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock.proto",
}
